apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS