name: $(why)_helm_release_$(SourceBranchName)_$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - master
      - release/*

resources:
  - repo: self

variables:
  azureContainerRegistry: "Azure Container Registry Prod"
  chartName: "mongodb"
  chartPath: "charts/bitnami/mongodb"
  ACRName: "cognigy.azurecr.io"
  ACRPath: "helm"
  ${{ if eq(variables['Build.Reason'], 'Manual') }}:
    why: Manual
  ${{ else }}:
    why: CD

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: helmChartRelease
    displayName: Create a new release tag and Helm Chart release
    jobs:
      - job: createNewRelease
        steps:
          - task: HelmInstaller@0
            displayName: Install Helm 3.8.2
            inputs:
              helmVersion: 3.8.2
              checkLatestHelmVersion: false

          - task: Docker@2
            displayName: Login into container registry
            inputs:
              command: 'login'
              containerRegistry: $(azureContainerRegistry)

          - bash: |
              helm version
              helmChartVersion="$(yq e '.version' $(chartPath)/Chart.yaml)"
              echo "Helm Chart" $(chartName) "version:" $helmChartVersion
              helm package --dependency-update $(chartPath)
              helm push ./$(chartName)-$helmChartVersion.tgz oci://$(ACRName)/$(ACRPath)